### ISSUE TITLE
nnsearch missing

### ISSUE THREAD

**Issue by csverma610** [NVIDIAGameWorks/kaolin#15] opened 2019-11-17 04:43 UTC
Hello,

I am new to Python and I installed Anaconda and thereafter followed the instructions given
on the website.

I get the following message:

(kaolin) csverma@blackhole:$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/35f6163f-1be0-4350-89a5-b885cc687dd6/csverma/Software/MLearn/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/mnt/35f6163f-1be0-4350-89a5-b885cc687dd6/csverma/Software/MLearn/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/mnt/35f6163f-1be0-4350-89a5-b885cc687dd6/csverma/Software/MLearn/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/mnt/35f6163f-1be0-4350-89a5-b885cc687dd6/csverma/Software/MLearn/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/mnt/35f6163f-1be0-4350-89a5-b885cc687dd6/csverma/Software/MLearn/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'

**Comment by krrish94** [comment] 2019-11-17 16:36
Seems to be a duplicate of https://github.com/NVIDIAGameWorks/kaolin/issues/9#issuecomment-554422485

**Closed as completed by krrish94** 2019-11-17 16:36 UTC
