### ISSUE TITLE
module 'site' has no attribute 'getsitepackages'

### ISSUE THREAD

**Issue by dongfengwang** [NVIDIAGameWorks/kaolin#6] opened 2019-11-15 03:57 UTC
When python setup.py install:

Building wheel kaolin-0.2.0+83002fe
--Building version 0.2.0+83002fe
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    build_deps()
  File "setup.py", line 43, in build_deps
    sp = site.getsitepackages()[0]
AttributeError: module 'site' has no attribute 'getsitepackages'

**Comment by Jean-Francois-Lafleche** [comment] 2019-11-15 16:11
Please comment out lines `42-45` in `setup.py` and try running the setup again. This will be addressed in an upcoming fix. Thanks for bringing it to our attention!

**Comment by vmlaker** [comment] 2019-11-21 21:22
This error also occurs when running Python from a virtualenv. The problem is that ``site`` module inside virtualenv is missing ``getsitepackages()`` method.

See https://github.com/pypa/virtualenv/issues/737#

Above link suggests a hack fix that involves using your system Python to find the list of site packages:

    python3 -c 'import site; print(site.getsitepackages())'

and editing file ``site.py`` inside your virtualenv by adding ``getsitepackages()`` method that returns the output of above command.

**Comment by ksamuel** [comment] 2019-12-28 21:47
`getsitepackages()` doesn't exist in venv in some versions of Python:

```
Python 3.7.6 (default, Dec 19 2019, 23:49:42) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getsitepackages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
>>> site.getsitepackage()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackage'
>>> site.getsitepackages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
>>> 
```

Your best bet is to iterate on `sys.path`, find one that you can write in (or one containing "site-packages" in the name) and put it on that.

If you do things like this, like a shot in the dark, we will have many back and forth on github. Your best bet is to write a unit test, and run it with all the Python version you support using tox. This will save you a lot of trouble.

**Comment by Caenorst** [comment] 2021-04-21 19:49
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and this issue is no longer current. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

**Closed as completed by Caenorst** 2021-04-21 19:49 UTC
Labels: bug
