### ISSUE TITLE
ShapeNet Meshes DataLoader Error (From Tutorial)

### ISSUE THREAD

**Issue by b7leung** [NVIDIAGameWorks/kaolin#95] opened 2019-12-14 21:40 UTC
I was following the tutorial [here](https://kaolin.readthedocs.io/en/latest/notes/datasets_tutorial.html), and my code is pretty simple:
```
shapenet_dir = "/data5/drone_machinelearning/Drone500v3/shapenet/core/ShapeNetCore.v1"
meshes = shapenet.ShapeNet_Meshes(root=shapenet_dir,categories=['plane'])
mesh_dataloader = DataLoader(meshes, batch_size = 10, shuffle=True, num_workers=8)
```
Directly accessing the dataset gives me no issues, eg:

```
print(meshes[0]['attributes'])
print(meshes[0]['data'])
```

But when I try to actually use the dataloader, I get some errors

```
for data in mesh_dataloader:
    x = data
    break`

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0.
 Got 17041 and 15629 in dimension 1 at /opt/conda/conda-
bld/pytorch_1573049387353/work/aten/src/TH/generic/THTensor.cpp:689
```
Also, if I set batch_size=1, I get the following:
```
TypeError: default_collate: batch must contain tensors, numpy arrays, 
numbers, dicts or lists; found <class 'pathlib.PosixPath'>
```

I'm using python 3.7.

**Comment by Jean-Francois-Lafleche** [comment] 2019-12-14 23:39
Hi @b7leung, the issue is that ShapeNet meshes each have different numbers of vertices and faces (and so different tensor dimensions). That means that they can't be collated by the default PyTorch collate function within the dataloader. The best solution depends on what you're trying to achieve, but one possible route is to reduce the batch size to 1, calculate the loss, and every <original_batch_size_number> iterations, call the backwards function. Hope that helps! We will look to improve the tutorials with more examples of how to load meshes like this in the future.

**Comment by Caenorst** [comment] 2021-04-23 14:23
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.

**Closed as completed by Caenorst** 2021-04-23 14:23 UTC
