### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by shuuchen** [NVIDIAGameWorks/kaolin#150] opened 2020-02-09 15:57 UTC
Hi,

Great work !
I just have some trouble running the DIB-Renderer Example as shown in https://github.com/NVIDIAGameWorks/kaolin/tree/master/examples/renderers/DIB-R

When I run 
```
$ python example.py
Segmentation fault
```

Any one could help ?

**Comment by TommyX12** [comment] 2020-02-12 18:15
Hi, please provide more information to reproduce the bug. What's your OS, Python version, PyTorch version, and CUDA version?

Also, make sure to perform the installation setup according to the README.

**Comment by shuuchen** [comment] 2020-02-13 11:37
Hi @TommyX12 
Thanks. I installed according to the README. The versions are:
OS: mac os high serria 10.13.4
python version: 3.6.9
pytorch version: 1.2
cuda version: 10.0

Hope this helps.

**Comment by zhjscut** [comment] 2020-02-14 05:35
I had the same problem. the error occurs when I execute `images = renderer.render_mesh(mesh)`.
OS: Ubuntu 14.04
python version: 3.6.6
pytorch version: 1.2.0
cuda version: 10.0
GPU: Tesla M40
However, it works regularly with GPU RTX 2080Ti.
Maybe it is because different GPU type?

**Comment by krrish94** [comment] 2020-04-06 18:35
@shuuchen @zhjscut Do you still face this issue?

**Comment by zhjscut** [comment] 2020-04-07 01:20
> @shuuchen @zhjscut Do you still face this issue?
At that time I had not solve this issue using Tesla M40, and at present I am using Blender as renderer, so I have no idea whether the new version of code works well.

**Comment by Caenorst** [comment] 2021-05-03 15:06
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.

**Closed as completed by Caenorst** 2021-05-03 15:06 UTC
Labels: how-to
