### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.nnsearch'

### ISSUE THREAD

**Issue by nikepupu** [NVIDIAGameWorks/kaolin#14] opened 2019-11-16 22:58 UTC
OS: ubuntu 18.0.4
platform: conda
python: 3.6.9
cuda: 10.1
pytorch: 1.3.1

After type in import kaolin as kal
I get this error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikepupu/Desktop/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/home/nikepupu/Desktop/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/home/nikepupu/Desktop/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/home/nikepupu/Desktop/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/home/nikepupu/Desktop/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'

**Comment by krrish94** [comment] 2019-11-16 23:10
Try stepping outside of the `kaolin` directory.

Duplicate of https://github.com/NVIDIAGameWorks/kaolin/issues/9#issuecomment-554422485

**Closed as completed by krrish94** 2019-11-16 23:10 UTC
