### ISSUE TITLE
DIB Renderer image reconstruction example

### ISSUE THREAD

**Issue by song4me** [NVIDIAGameWorks/kaolin#289] opened 2020-07-08 23:57 UTC
Hi,
I am trying to run the DIB Renderer image reconstruction example from here
kaolin-master/examples/ImageRecon/Dib/train.py
As written in other messages here, the code does not match the architectural changes made in Kaolin. I managed to modify the code myself to allow network training (will be glad to share if useful to others), however I get this error on the validation phase:

`  File "/home/ubuntu/Dev/FaceReconstruction/kaolin-master/examples/ImageRecon/Dib/train.py", line 298, in <module>
    trainer.validate()
  File "/home/ubuntu/Dev/FaceReconstruction/kaolin-master/examples/ImageRecon/Dib/train.py", line 219, in validate
    for i, data in enumerate(tqdm(dataloader_val), 0):
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/tqdm-4.32.1-py3.6.egg/tqdm/_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ubuntu/miniconda3/envs/kaolin36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 81, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'pathlib.PosixPath'>`

**Comment by Shubhamjain27** [comment] 2020-07-09 11:46
The issue is because of class Shapenet_Images. If you see the output, one of the attributes is 'name', which is of type pathlib.Posixpath. I fixed it by creating a subclass that omits the attribute 'name' from the output.

**Comment by song4me** [comment] 2020-07-12 04:33
Thanks!
I see you have also corrected the code.
I'll test with your new version and see how it goes

**Comment by Caenorst** [comment] 2021-04-23 14:13
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

You can take a look at our new DIB-R example which should be simpler, and using our newly released Omniverse Kaolin App :)

Closing the bug as it is no longer relevant to this repo.

**Closed as completed by Caenorst** 2021-04-23 14:13 UTC
