### ISSUE TITLE
No module named 'kaolin.nnsearch'

### ISSUE THREAD

**Issue by Godoakos** [NVIDIAGameWorks/kaolin#21] opened 2019-11-18 04:53 UTC
After a fresh install in a new python 3.7 conda env, importing kaolin fails.
I'm on Ubuntu 18.04, Python 3.7.3.

```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/godoakos/Apps/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/home/godoakos/Apps/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/home/godoakos/Apps/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/home/godoakos/Apps/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/home/godoakos/Apps/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'
```

**Comment by krrish94** [comment] 2019-11-18 04:58
Looks like a duplicate of https://github.com/NVIDIAGameWorks/kaolin/issues/3#issue-523193927

@Godoakos It will be great if you confirm that this is indeed the fix

**Comment by Godoakos** [comment] 2019-11-18 05:13
Thanks for the fast reply @krrish94 !

It fixed it: when running the interpreter in the kaolin directory the import statement fails, running it outside makes it succeed consistently.
Seems like python was a bit greedy with paths.

Sorry for the duplicate.

**Comment by krrish94** [comment] 2019-11-18 05:49
Thanks for the update. Glad it worked.

**Closed as completed by krrish94** 2019-11-18 05:49 UTC
